'use client';

import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { OwnershipTable } from '@/components/cap-table/OwnershipTable';
import { OwnershipChart } from '@/components/cap-table/OwnershipChart';
import { Printer } from 'lucide-react';

interface SharedCapTableData {
  organization_name: string;
  share_classes: Array<{
    id: string;
    name: string;
    authorized_shares: number;
    reserved_shares: number;
    issued_shares: number;
    available_shares: number;
    price_per_share: number | null;
  }>;
  stakeholders: Array<{
    id: string;
    name: string;
    email: string | null;
    role_title: string | null;
    holdings: Array<{
      share_class_id: string;
      share_class_name: string;
      shares_held: number;
      ownership_percentage: number;
    }>;
    total_shares: number;
    total_ownership_percentage: number;
  }>;
  totals: {
    total_authorized: number;
    total_issued: number;
    total_reserved: number;
    total_available: number;
  };
}

interface SharedCapTableViewProps {
  data: SharedCapTableData;
}

/**
 * Read-only shared cap table view with print/PDF support.
 * Renders a clean, branded layout with ownership table and donut chart.
 */
export function SharedCapTableView({ data }: SharedCapTableViewProps) {
  return (
    <div className="min-h-screen bg-gray-50">
      <div className="mx-auto max-w-5xl px-4 py-8">
        {/* Header */}
        <div className="mb-8 flex items-start justify-between print:mb-4">
          <div>
            <h1 className="text-3xl font-bold print:text-2xl">{data.organization_name}</h1>
            <p className="text-lg text-muted-foreground">Cap Table</p>
            <p className="text-sm text-muted-foreground">
              As of {new Date().toLocaleDateString('en-US', {
                year: 'numeric',
                month: 'long',
                day: 'numeric',
              })}
            </p>
          </div>
          <Button
            variant="outline"
            size="sm"
            onClick={() => window.print()}
            className="print:hidden"
          >
            <Printer className="mr-1 h-4 w-4" />
            Print / Save as PDF
          </Button>
        </div>

        {/* Share class summary cards */}
        <div className="mb-6 grid gap-4 md:grid-cols-2 lg:grid-cols-4 print:grid-cols-4">
          <Card>
            <CardContent className="pt-6">
              <p className="text-sm text-muted-foreground">Total Authorized</p>
              <p className="text-2xl font-bold">{data.totals.total_authorized.toLocaleString()}</p>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="pt-6">
              <p className="text-sm text-muted-foreground">Total Issued</p>
              <p className="text-2xl font-bold">{data.totals.total_issued.toLocaleString()}</p>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="pt-6">
              <p className="text-sm text-muted-foreground">Total Reserved</p>
              <p className="text-2xl font-bold">{data.totals.total_reserved.toLocaleString()}</p>
            </CardContent>
          </Card>
          <Card>
            <CardContent className="pt-6">
              <p className="text-sm text-muted-foreground">Total Available</p>
              <p className="text-2xl font-bold">{data.totals.total_available.toLocaleString()}</p>
            </CardContent>
          </Card>
        </div>

        {/* Ownership section: table + chart */}
        <div className="grid gap-6 lg:grid-cols-3 print:grid-cols-3">
          <Card className="lg:col-span-2">
            <CardHeader>
              <CardTitle>Ownership Summary</CardTitle>
            </CardHeader>
            <CardContent>
              <OwnershipTable
                stakeholders={data.stakeholders as any}
                totals={data.totals}
                readOnly
              />
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Ownership Distribution</CardTitle>
            </CardHeader>
            <CardContent>
              <OwnershipChart
                stakeholders={data.stakeholders}
                totalIssued={data.totals.total_issued}
              />
            </CardContent>
          </Card>
        </div>

        {/* Footer */}
        <p className="mt-8 text-center text-xs text-muted-foreground print:mt-4">
          Generated by DevLabs CFO
        </p>
      </div>
    </div>
  );
}
